#!/usr/bin/env Rscript
options(stringsAsFactors = FALSE)
args <- commandArgs(trailingOnly = FALSE)
script_arg <- grep("^--file=", args, value = TRUE)
script_file <- if (length(script_arg)) normalizePath(sub("^--file=", "", script_arg[1]), winslash = "/") else normalizePath(sys.frames()[[1]]$ofile, winslash = "/")
CLOSEOUT <- normalizePath(file.path(dirname(script_file), ".."), winslash = "/")

read_all <- function(f) paste(readLines(f, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
fig_code <- read_all(file.path(CLOSEOUT, "code", "13_make_submission_figures.R"))
text_code <- read_all(file.path(CLOSEOUT, "code", "14_build_manuscript_text.R"))
methods <- read_all(file.path(CLOSEOUT, "manuscript_support", "Methods_production.md"))
legends <- read_all(file.path(CLOSEOUT, "manuscript_support", "Figure_legends_production.md"))

stopifnot(grepl("Patients from zero-observation centres", fig_code, fixed = TRUE))
stopifnot(!grepl("Excluded zero-observation centres", fig_code, fixed = TRUE))
stopifnot(grepl("Figure2_RNA_core_NES\"", fig_code))
stopifnot(grepl("Figure3_Protein_core_NES\"", fig_code))
stopifnot(!length(list.files(file.path(CLOSEOUT, "figures"), pattern = "Figure[23]_.*_robustness", full.names = TRUE)))
stopifnot(!grepl("Figure2_RNA_core_NES_robustness|Figure3_Protein_core_NES_robustness", paste(methods, legends), ignore.case = TRUE))
stopifnot(grepl("Four patients from three zero-observation centres were excluded from the positivity-supported estimand.", legends, fixed = TRUE))
stopifnot(!grepl("dagger|section symbols|concordant significance", legends, ignore.case = TRUE))
stopifnot(grepl("Day-1, day-3 and day-5 molecular measurements were analysed in separate time-specific prognostic models.", methods, fixed = TRUE))
stopifnot(!grepl("time-updated exposures|time-dependent covariate", paste(methods, text_code), ignore.case = TRUE))
stopifnot(grepl("TNF-α signaling via NF-κB", fig_code, fixed = TRUE))
stopifnot(grepl("IL-6/JAK/STAT3 signaling", fig_code, fixed = TRUE))
cat("Submission semantic interface tests passed.\n")
