# Sanitized derivative of the frozen workstation-specific configuration.
# Statistical seeds, landmarks, expected counts and logical inputs are unchanged.
options(stringsAsFactors = FALSE, warn = 1)
set.seed(20260711)

PROJECT_DIR <- normalizePath(
  Sys.getenv("SIC_PROJECT_DIR", unset = getwd()),
  winslash = "/",
  mustWork = TRUE
)

SOURCE_DIR <- Sys.getenv("CMAISE_DATA_DIR", unset = "")
if (!nzchar(SOURCE_DIR)) {
  stop("Set CMAISE_DATA_DIR to an authorised OMIX011182 data directory")
}
SOURCE_DIR <- normalizePath(SOURCE_DIR, winslash = "/", mustWork = TRUE)

OUT_ROOT <- normalizePath(
  Sys.getenv(
    "SIC_OUTPUT_DIR",
    unset = file.path(PROJECT_DIR, "private_outputs", "SIC_reanalysis_2026-07-11")
  ),
  winslash = "/",
  mustWork = FALSE
)

AUDIT_DIR <- file.path(OUT_ROOT, "00_audit")
RNA_OUT <- file.path(OUT_ROOT, "01_RNA_TMM")
PROTEIN_OUT <- file.path(OUT_ROOT, "02_Protein")
CROSS_OUT <- file.path(OUT_ROOT, "03_CrossOmics")
FIGURE_OUT <- file.path(OUT_ROOT, "04_Figures_Tables")
LOG_OUT <- file.path(OUT_ROOT, "99_logs")
AVAIL_OUT <- file.path(OUT_ROOT, "06_Availability_IPW_final")

local_r_lib <- Sys.getenv("R_LIBS_USER", unset = "")
if (nzchar(local_r_lib)) .libPaths(c(local_r_lib, .libPaths()))

for (d in c(
  OUT_ROOT, AUDIT_DIR, RNA_OUT, PROTEIN_OUT, CROSS_OUT,
  FIGURE_OUT, AVAIL_OUT, LOG_OUT
)) {
  dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

INPUT <- list(
  clinical = file.path(SOURCE_DIR, "SIC_504_baseline_carried_forward_annotation.csv"),
  raw_clinical = file.path(dirname(SOURCE_DIR), "OMIX011182-01.csv"),
  rna_counts = file.path(SOURCE_DIR, "OMIX011182-04.txt"),
  protein = file.path(SOURCE_DIR, "OMIX011182-05.xlsx"),
  protein_qc = file.path(
    SOURCE_DIR,
    "SIC_detailed_analysis_phase1",
    "13_protein_feature_qc.csv"
  ),
  hallmark = file.path(SOURCE_DIR, "h.all.v2026.1.Hs.symbols.gmt"),
  frozen_gene_map = file.path(AUDIT_DIR, "ensembl_gene_map_orgHs_3.20_frozen.tsv")
)

ENTRY_DAY <- c(D1 = 0, D3 = 2, D5 = 4)
AVAIL_ENTRY <- c(lower = 3.75, primary = 4.00, upper = 4.25)
AVAIL_MODEL_SPECS <- c("SOFA_D3", "SOFA_noD3", "PF_PLT_D3", "PF_PLT_noD3")
EXPECTED <- data.frame(
  Omics = rep(c("RNA", "Protein"), each = 3),
  Time = rep(c("D1", "D3", "D5"), 2),
  N = c(504, 420, 320, 168, 147, 114),
  Events = c(84, 67, 53, 27, 18, 14)
)

# The frozen gene map is generated by 00b before later stages consume it.
required_input_names <- setdiff(names(INPUT), "frozen_gene_map")
required <- unlist(INPUT[required_input_names], use.names = TRUE)
missing <- required[!file.exists(required)]
if (length(missing)) {
  stop("Missing required inputs:\n", paste(missing, collapse = "\n"))
}

message("Authorised source directory configured")
message("Writable output: ", OUT_ROOT)
