build_clinical_workbook <- function(clinical_dir) {
  clinical_dir <- normalizePath(clinical_dir, winslash = "/", mustWork = TRUE)
  output <- file.path(clinical_dir, "Clinical_Table1_and_Univariable_Cox.xlsx")

  sheet_inputs <- c(
    Table1_Baseline = "Table1_baseline_characteristics.csv",
    Univariable_Cox = "Clinical_univariable_Cox.csv",
    Sparse_Event_Audit = "Clinical_sparse_event_audit.csv",
    Infection_Mapping = "Clinical_infection_source_mapping.csv",
    Drop5_Time_Sensitivity = "Clinical_drop5_event_time_sensitivity.csv",
    Variable_Dictionary = "Clinical_variable_dictionary.csv",
    Diagnostics = "Clinical_analysis_diagnostics.csv"
  )
  input_paths <- file.path(clinical_dir, unname(sheet_inputs))
  missing <- input_paths[!file.exists(input_paths)]
  if (length(missing)) {
    stop("Missing frozen clinical table input(s): ", paste(basename(missing), collapse = ", "))
  }

  read_frozen_csv <- function(path) {
    utils::read.csv(path, check.names = FALSE, stringsAsFactors = FALSE, na.strings = c("", "NA"))
  }

  readme <- data.frame(
    Item = c(
      "Cohort",
      "Recommended manuscript placement",
      "Table 1 summary",
      "Cox model",
      "Multiplicity and assumptions",
      "Infection source",
      "Verified coding and units",
      "High-priority endpoint risk",
      "Interpretation boundary",
      "Reproducibility"
    ),
    Description = c(
      "504 day-1 patients meeting the frozen SIC cohort definition.",
      "Table1_Baseline is the manuscript baseline table; Univariable_Cox is supplementary evidence.",
      "Continuous variables are summarised using the frozen production table; arterial pH and calcium remain excluded because of missingness.",
      "Separate univariable Cox models use the frozen 60-day survival endpoint and Efron handling of ties.",
      "BH-FDR and proportional-hazards diagnostics are reported; sparse or zero-event levels require cautious interpretation.",
      "The prespecified six-category infection-source consolidation is retained.",
      "Sex coding, author-confirmed unit corrections and event-time provenance follow the frozen audit outputs.",
      "Hospital length of stay is not treated as a baseline predictor.",
      "Univariable associations are descriptive and do not establish independent effects or causality.",
      "This workbook is assembled without refitting models from the frozen CSV outputs generated by 09_build_clinical_tables.R."
    ),
    check.names = FALSE
  )

  wb <- openxlsx::createWorkbook()
  openxlsx::addWorksheet(wb, "README")
  openxlsx::writeDataTable(wb, "README", readme, tableStyle = "TableStyleMedium2")
  openxlsx::setColWidths(wb, "README", cols = 1, widths = 34)
  openxlsx::setColWidths(wb, "README", cols = 2, widths = 95)
  wrap_style <- openxlsx::createStyle(wrapText = TRUE, valign = "top")
  openxlsx::addStyle(
    wb, "README", style = wrap_style,
    rows = 1:(nrow(readme) + 1), cols = 1:2,
    gridExpand = TRUE, stack = TRUE
  )

  for (sheet in names(sheet_inputs)) {
    dat <- read_frozen_csv(file.path(clinical_dir, sheet_inputs[[sheet]]))
    openxlsx::addWorksheet(wb, sheet)
    openxlsx::writeDataTable(wb, sheet, dat, tableStyle = "TableStyleMedium2")
    openxlsx::freezePane(wb, sheet, firstRow = TRUE)
    openxlsx::setColWidths(wb, sheet, cols = seq_len(ncol(dat)), widths = "auto")
  }

  openxlsx::saveWorkbook(wb, output, overwrite = TRUE)
  if (!file.exists(output) || file.info(output)$size <= 1000) {
    stop("Clinical workbook production failed: ", output)
  }
  output
}

if (sys.nframe() == 0L && !interactive()) {
  out_root <- Sys.getenv("SIC_OUTPUT_DIR", unset = "")
  if (!nzchar(out_root)) stop("Set SIC_OUTPUT_DIR before running this script")
  workbook <- build_clinical_workbook(file.path(out_root, "05_Clinical_Tables"))
  message("Created: ", workbook)
}
